In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import scale
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import make_regression

In [2]:
import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('fivethirtyeight')
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [3]:
data=pd.read_csv('dataset_for_ml_models.zip')
data.head()

,YYYY,YYYYMM,INCOME,HOMEOWN,AGE,INFL_HOMEAMT,INFL_INVAMT,REGION_Northeast,REGION_South,REGION_West,...,EHSGRD_NA,EHSGRD_No,EHSGRD_Yes,ECLGRD_NA,ECLGRD_No,ECLGRD_Yes,POLAFF_Democrat,"POLAFF_Independent, No Preference",POLAFF_NA,POLAFF_Republican
0,2006,200609,52000,1,52,386127.458739,166892.013889,0,0,1,...,0,0,1,0,0,1,1,0,0,0
1,2006,200609,150000,1,70,386127.458739,96283.854167,1,0,0,...,0,0,1,0,0,1,0,1,0,0
2,2006,200609,38000,1,60,386127.458739,437017.193297,0,1,0,...,0,0,1,0,1,0,0,1,0,0
3,2006,200609,175000,1,53,386127.458739,962838.541667,0,0,1,...,0,0,1,0,0,1,0,0,0,1
4,2006,200609,24000,2,59,386127.458739,6420.207396,0,1,0,...,0,0,1,0,0,1,0,0,0,1

In [4]:
data['AGE']=scale(data['AGE'])
data['INFL_HOMEAMT']=scale(data['INFL_HOMEAMT'])
data['INFL_INVAMT']=scale(data['INFL_INVAMT'])
data['INCOME']=scale(data['INCOME'])
data['YYYY'] = LabelEncoder().fit_transform(data['YYYY'])
data.head()

,YYYY,YYYYMM,INCOME,HOMEOWN,AGE,INFL_HOMEAMT,INFL_INVAMT,REGION_Northeast,REGION_South,REGION_West,...,EHSGRD_NA,EHSGRD_No,EHSGRD_Yes,ECLGRD_NA,ECLGRD_No,ECLGRD_Yes,POLAFF_Democrat,"POLAFF_Independent, No Preference",POLAFF_NA,POLAFF_Republican
0,0,200609,-0.562350,1,0.007788,-3.488944e-15,-0.360122,0,0,1,...,0,0,1,0,0,1,1,0,0,0
1,0,200609,0.514108,1,1.077950,-3.488944e-15,-0.454185,1,0,0,...,0,0,1,0,0,1,0,1,0,0
2,0,200609,-0.716130,1,0.483415,-3.488944e-15,-0.000262,0,1,0,...,0,0,1,0,1,0,0,1,0,0
3,0,200609,0.788715,1,0.067241,-3.488944e-15,0.700235,0,0,1,...,0,0,1,0,0,1,0,0,0,1
4,0,200609,-0.869910,2,0.423962,-3.488944e-15,-0.573901,0,1,0,...,0,0,1,0,0,1,0,0,0,1

In [5]:
train, test = train_test_split(data, test_size = 0.3, random_state= 1)

In [6]:
x_train=train.drop(['INCOME','YYYYMM'],axis=1)
y_train=train['INCOME']
x_test=test.drop(['INCOME','YYYYMM'],axis=1)
y_test=test['INCOME']

In [7]:
x_train.head()

,YYYY,HOMEOWN,AGE,INFL_HOMEAMT,INFL_INVAMT,REGION_Northeast,REGION_South,REGION_West,SEX_Male,MARRY_Married/partner,...,EHSGRD_NA,EHSGRD_No,EHSGRD_Yes,ECLGRD_NA,ECLGRD_No,ECLGRD_Yes,POLAFF_Democrat,"POLAFF_Independent, No Preference",POLAFF_NA,POLAFF_Republican
32006,10,1,0.959043,1.064999,-0.000262,0,1,0,1,1,...,0,0,1,0,0,1,1,0,0,0
49796,13,1,-0.884014,-0.344855,-0.581041,1,0,0,1,1,...,0,0,1,0,1,0,0,1,0,0
22366,9,1,0.126695,-0.013631,0.378693,0,0,0,1,1,...,0,0,1,0,0,1,0,1,0,0
14192,7,1,0.780682,-0.178743,-0.438797,0,0,1,1,1,...,0,0,1,0,1,0,1,0,0,0
2132,1,1,-0.230026,-0.072795,-0.000262,1,0,0,0,1,...,0,0,1,0,0,1,1,0,0,0

In [8]:
#use svr model
from sklearn.pipeline import make_pipeline
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
svm_poly_reg = make_pipeline(StandardScaler(), SVR(kernel="linear", C=0.01, epsilon=0.1))
svm_poly_reg.fit(x_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svr', SVR(C=0.01, kernel='linear'))])

In [10]:
from sklearn.metrics import mean_squared_error

y = svm_poly_reg.predict(x_test)
lin_rmse = mean_squared_error(y_test, y, squared=False)

In [11]:
lin_mse=mean_squared_error(y_test, y)
print(lin_rmse)
print(lin_mse)

0.7530684823979875
0.567112139181208

In [12]:
#xgboost
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import scale
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import make_regression

In [13]:
reg = GradientBoostingRegressor(learning_rate =0.1, max_depth= 5, n_estimators=100)
model_xgboost=reg.fit(x_train, y_train)
mse = mean_squared_error(y_test, reg.predict(x_test))
rmse = mean_squared_error(y_test, reg.predict(x_test),squared=False)

In [14]:
print("The mean squared error (MSE) on test set: {:.4f}".format(mse))
print("The RMSE on test set: {:.4f}".format(rmse))
print("The R_square on train set: {:.4f}".format(model_xgboost.score(x_train, y_train)))
print("The R_square on test set: {:.4f}".format(model_xgboost.score(x_test, y_test)))

The mean squared error (MSE) on test set: 0.4397
The RMSE on test set: 0.6631
The R_square on train set: 0.5936
The R_square on test set: 0.5392

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import scale
from sklearn.linear_model import Lasso
from sklearn.linear_model import LassoCV
#lasso

lambds=np.logspace(-5,2,200)
alpha_lasso =lambds
lasso = Lasso()
coefs_lasso = []


for i in alpha_lasso:
    lasso.set_params(alpha = i,tol=10-3,fit_intercept=True)
    lasso.fit(x_train, y_train)
    coefs_lasso.append(lasso.coef_)
    
from sklearn.metrics import mean_squared_error
lasso.set_params(alpha = 10**-2,tol=10-3,fit_intercept=True)
model_lasso = lasso.fit(x_train, y_train)
coef = pd.Series(model_lasso.coef_,index=x_train.columns)
print(coef[coef != 0].abs().sort_values(ascending = False))
y_pred = model_lasso.predict(x_test)

HOMEOWN                              0.580454
INFL_HOMEAMT                         0.443390
MARRY_Married/partner                0.289477
EGRADE_17                            0.204015
INFL_INVAMT                          0.197915
EGRADE_12                            0.145995
SEX_Male                             0.107912
REGION_West                          0.077916
AGE                                  0.074752
ECLGRD_No                            0.071835
EGRADE_14                            0.062681
REGION_Northeast                     0.054578
EHSGRD_No                            0.053823
YYYY                                 0.041046
EGRADE_13                            0.033641
EGRADE_16                            0.012419
POLAFF_Independent, No Preference    0.008688
ECLGRD_Yes                           0.000293
dtype: float64

In [19]:
# MSE
mse_lasso = np.sqrt(mean_squared_error(y_test, y_pred))
print("MSE:", mse_lasso)
# RMSE
rmse_lasso = np.sqrt(mean_squared_error(y_test, y_pred,squared=False))
print("RMSE:", rmse_lasso)

MSE: 0.7576922855905254
RMSE: 0.8704552174526415